
import edu.huji.cs.netutils.files.CaptureFileFactory; { Used to import a file to capture data packet 
import edu.huji.cs.netutils.files.CaptureIterator;          from file directory}
import edu.huji.cs.netutils.parse.EthernetFrame;
import edu.huji.cs.netutils.parse.FiveTuple;
import edu.huji.cs.netutils.parse.IPFactory;
import edu.huji.cs.netutils.parse.IPv4Packet;        
import edu.huji.cs.netutils.parse.TCPPacket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class TCPDump extends javax.swing.JFrame {
String dura[]={"0:00:13","0:00:00","0:01:01","0:00:14","0:00:12","0:00:04","0:00:17","0:00:11","0:00:24","0:00:16","0:01:23","0:00:49","0:00:36","0:00:15","0:00:06","0:00:59","0:00:48","0:01:36"};
    /**
     * Creates new form TCPDump
     *// Created new Dump file                
    public TCPDump() {
        initComponents();
        jTextField1.setText(PacketCapturing_2.fname);
    }
// tcpdump is a common packet analyzer that runs under the command line. It allows the user to display TCP/IP and other packets being transmitted or received over a network to which the computer is attached.
    /**
     * This method is called from within the constructor to initialize the form.
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();    // { javax.swing. Provides a set of "lightweight" (all-Java language) components that, to the maximum degree possible, work the same on all platforms.} //

        jButton1.setText("jButton1");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(50, 70, 490, 30);   // Jpanel  provides a plateform to add features to java frames by adding back ground colour within a specified text area) //                                                      
        jButton2.setText("Import ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(560, 70, 140, 30);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);
        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 150, 700, 350);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("J-Honeypot Intrusion Detection and Deception Tool ");
            } // The text area is secified within intrusion detection //

